language: android
sudo: required
dist: precise
group: edge
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - build-tools-28.0.3
    - android-28
    - extra

services:
  - postgresql
  - mysql

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

before_script:
  - mysql -e "create database if not exists testdb;" -uroot
  - psql -c 'create database testdb;' -U postgres
  - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
